name: Issue Triage

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  triage:
    permissions:
      contents: read
      id-token: write
      issues: write
    uses: aws/aws-durable-execution-ci/.github/workflows/issue-triage.yml@8de63fa646c1b7b778829126cf53b7874074795e
    secrets: inherit
